version: "3.8"

services:
  primary_postgres:
    image: 'bitnami/postgresql:latest'
    container_name: primary_postgres
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=abc123
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=abc123
      - POSTGRESQL_USERNAME=sonle
      - POSTGRESQL_PASSWORD=sonle123
      - POSTGRESQL_DATABASE=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql/primary_server:/bitnami/postgresql
      - ./data/postgresql/primary_server/conf/:/bitnami/postgresql/conf/
      - ./containers/postgresql/primary_init.sql:/docker-entrypoint-initdb.d/primary_init.sql
#    networks:
#      - sonle

  standby_postgres:
    image: 'bitnami/postgresql:latest'
    container_name: standby_postgres
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=abc123
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=abc123
      - POSTGRESQL_MASTER_HOST=primary_postgres
      - POSTGRESQL_USERNAME=sonle
      - POSTGRESQL_PASSWORD=sonle123
      - POSTGRESQL_DATABASE=postgres
    ports:
      - '5433:5432'
    volumes:
      - ./data/postgresql/standby_server:/bitnami/postgresql
      - ./data/postgresql/standby_server/conf/:/bitnami/postgresql/conf/
    depends_on:
    - primary_postgres
#    networks:
#      - sonle

  kafka:
    image: quay.io/debezium/kafka:2.5
    container_name: broker
    ports:
     - '9092:9092'
     - '9093:9093'
    environment:
     - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
     - BROKER_ID=1
     - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
#    networks:
#      - sonle

  connect:
    image: quay.io/debezium/connect:2.5
    container_name: connect
    ports:
     - 8083:8083
    links:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
#    networks:
#      - sonle

#networks:
#  sonle:
#    name: sonle
#    driver: bridge
